appointment/urls.py
from django.urls import path
from . views import *

urlpatterns = [
    path('add/', create_view, name='add_appointment'),
    path('appointment/ajax/load-doctors/', load_doctors, name='ajax_load_doctors'),

    path('total_appointments/', total_appointments, name='total_appointments'),
    path('user_appointments/<int:_id>/', user_appointments, name='user_appointments'),

    path("prescription_pdf/<int:_id>/", prescription_pdf, name="prescription_pdf"),
    
    path("my_appointments/", my_appointments, name="my_appointments"),
]

chat/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('chat/', views.home, name='chat'),
    path('<str:room>/', views.room, name='room'),
    path('checkview', views.checkview, name='checkview'),
    path('send', views.send, name='send'),
    path('getMessages/<str:room>/', views.getMessages, name='getMessages'),
]

project/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf.urls.static import static
from django.conf import settings

from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi


schema_view = get_schema_view(
   openapi.Info(
      title="Needs Automatic Prescription API",
      default_version='v1',
      description="Automatic Prescription description",
      terms_of_service="https://www.needs.com/policies/terms/",
      contact=openapi.Contact(email="needs@mail.com"),
      license=openapi.License(name="Needs License"),
   ),
   public=True,
   permission_classes=[permissions.AllowAny],
)

from helper.views import *
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home,name='home'),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('accounts/', include('accounts.urls')),
    path('find-doctor/', include('find_doctors.urls')),
    path('query/', include('querys.urls')),
    path('appointment/', include('appointment.urls')),
    path('payment/', include('payment.urls')),
    path('openapi/', include('openapi.urls')),
    path('', include('ambulance.urls')),
    path('', include('chat.urls')),
    path('doctor_dashboard/', include('doctor_dashboard.urls')),
    
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),

    
   #  path('ambulance-list/', AmbulanceList.as_view(), name='ambulance'),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_header  =  "Needs Healthcare admin"  
admin.site.site_title  =  "Needs Healthcare admin site"
admin.site.index_title  =  "Needs Healthcare Admin"

appointment/models.py
from django.db import models
import datetime
from multiselectfield import MultiSelectField
from ambulance.models import PossiblePhoneNumberField


# Create your models here.
class Department(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Doctor(models.Model):
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Patients(models.Model):
    SEX = [
        ('Male', 'Male'),
        ('Female', 'Female'),
        ('Others', 'Others'),
    ]
    user = models.ForeignKey("accounts.User", on_delete=models.CASCADE)
    department = models.ForeignKey(Department, on_delete=models.SET_NULL, null=True)
    doctor = models.ForeignKey(Doctor, on_delete=models.SET_NULL, null=True)
    age = models.PositiveSmallIntegerField()
    sex = models.CharField(choices=SEX, default='Male', max_length=6, )
    email = models.EmailField(max_length=255)
    phone = PossiblePhoneNumberField(blank=True, default="")
    describe_your_problems = models.TextField()
    report = models.FileField(null=True, blank=True)

    def __str__(self):
        return self.email
    
    class Meta:
      verbose_name = "Appointment"
      ordering = ['-id',]


class PatientAppointmentAnswer(models.Model):
    CHOICES = (
        ('Before Breakfast', 'Before Breakfast'),
        ('After Breakfast', 'After Breakfast'),
        ('Before Lunch', 'Before Lunch'),
        ('After Lunch', 'After Lunch'),
        ('Before Dinner', 'Before Dinner'),
        ('After Dinner', 'After Dinner'),
    )

    patient = models.ForeignKey(Patients, on_delete=models.CASCADE)
    test = models.CharField(max_length=255, null=True, blank=True)
    medicine_one = models.CharField(max_length=255, null=True, blank=True)
    medicine_two = models.CharField(max_length=255, null=True, blank=True)
    medicine_three = models.CharField(max_length=255, null=True, blank=True)
    medicine_others = models.CharField(max_length=500, null=True, blank=True)
    advice = models.TextField(null=True, blank=True)
    date = models.DateField(default=datetime.date.today)
    medicine_eating_time = MultiSelectField(choices=CHOICES, max_choices=3, max_length=200)

    def __str__(self):
        return self.patient.email

    class Meta:
      verbose_name = "Patient Appointment Answer"

appointment/forms.py
from django import forms
from .models import Patients, Doctor


class PatientForm(forms.ModelForm):
  class Meta:
    model = Patients
    # fields = '__all__'
    exclude = ['user', ]

  def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)
    self.fields['doctor'].queryset = Doctor.objects.none()

    if 'department' in self.data:
      try:
        department_id = int(self.data.get('department'))
        self.fields['doctor'].queryset = Doctor.objects.filter(department_id=department_id).order_by('name')
      except (ValueError, TypeError):
        pass  # invalid input from the client; ignore and fallback to empty City queryset
    elif self.instance.pk:
      self.fields['doctor'].queryset = self.instance.department.doctor_set.order_by('name')
  
  def read_user(self):
    if self.instance: 
        return self.instance.sku
    else: 
        return self.fields['sku']

  
class PatientAppointmentAnswerForm(forms.Form):
  test =forms.CharField(required=False)
  medicine_one =forms.CharField(required=False)
  medicine_two =forms.CharField(required=False)
  medicine_three =forms.CharField(required=False)
  medicine_others =forms.CharField(required=False)
  medicine_eating_time = forms.CharField(required=False)
  advice =forms.CharField(required=False, widget=forms.Textarea(attrs={"rows":5, "cols":20, 'placeholder': 'Advice something...'}))

  def __str__(self):
    return f"{self.medicine_one}"

appointment/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from django.http import Http404, HttpResponse
from .forms import PatientForm, PatientAppointmentAnswerForm
from .models import Patients, Doctor, PatientAppointmentAnswer
from django.template.loader import get_template
from xhtml2pdf import pisa
from django.views.decorators.csrf import csrf_exempt
from django.core.mail import send_mail


# Create your views here.
# @api_view(['POST',])
@csrf_exempt
def create_view(request):
  default_user = {
    'user':request.user
  }

  form = PatientForm(initial=default_user or None)
  if request.method == 'POST':
    form = PatientForm(request.POST or None,  request.FILES)
    if form.is_valid():
      form = form.save(commit=False)
      form.user = request.user
      send_mail(
      'Appointment create',
      'An appointment has beed cerated. Please visit your dashboard.',
      'Needs Health Care',
      ['rakibulislam8226@gmail.com'],
      fail_silently=False,
  )
      form.save()

      messages.warning(request, 'Your appointment are pending for payment. Payment now for confirm your appointment.')
      return redirect('/payment')
  return render(request, 'appointment/home.html', {'form': form})


# AJAX
def load_doctors(request):
  department_id = request.GET.get('department_id')
  doctors = Doctor.objects.filter(department_id=department_id).all()
  return render(request, 'appointment/doctor_dropdown_list_options.html', {'doctors': doctors})



def total_appointments(request):
  total = Patients.objects.all()

  context ={
    'total': total
  }
  return render(request ,'appointment/appointment_list.html', context)



def my_appointments(request):
  total=Patients.objects.filter(user=request.user)

  context={
    'total': total,
    'total_appointment':len(total),
  }
  return render(request,'appointment/appointment_list.html',context)

 

def user_appointments(request,_id):
  try:
    data = Patients.objects.get(id =_id)
    answers = PatientAppointmentAnswer.objects.filter(patient = data)
  except Patients.DoesNotExist:
    raise Http404('Data does not exist')
    
  if request.method == 'POST':
    form = PatientAppointmentAnswerForm(request.POST)
    if form.is_valid():
      answers = PatientAppointmentAnswer(
      test=form.cleaned_data['test'],
      medicine_one=form.cleaned_data['medicine_one'],
      medicine_two=form.cleaned_data['medicine_two'],
      medicine_three=form.cleaned_data['medicine_three'],
      medicine_others=form.cleaned_data['medicine_others'],
      medicine_eating_time=form.cleaned_data['medicine_eating_time'],
      advice=form.cleaned_data['advice'],
      patient=data)
      answers.save()
      messages.success(request, 'successfully submit appointment answer.')
      return redirect(f'/appointment/user_appointments/{_id}')
  else:
      form = PatientAppointmentAnswerForm()

  context = {
    'data':data,
    'form':form,
    'record':answers,
  }
  return render(request,'appointment/appointment_details.html',context)



def render_to_pdf(template_src, context_dict={}):
  template = get_template(template_src)
  html = template.render(context_dict)
  response = HttpResponse(content_type='application/pdf')
  pdf_status = pisa.CreatePDF(html, dest=response)

  if pdf_status.err:
    return HttpResponse('Some errors were encountered <pre>' + html + '</pre>')

  return response


def prescription_pdf(request, _id):
  template_name = "appointment/prescription_pdf.html"
  records = PatientAppointmentAnswer.objects.get(id = _id)

  return render_to_pdf(
    template_name,
    {
      "record": records,
    },
  )

templates/appointment/appointment.html
{% extends "base/base.html" %}
{% load crispy_forms_tags %}


{% block body %}
<div class="col-md-6 offset-md-3">
  <form action="/" method="post">
    <br>
    <h4 style="text-align: center; color:rgb(7, 77, 30)">Create an appointment.</h4><br>
    {% csrf_token %}
    {{ form | crispy }}
    <div class="">
      <button type="submit" class="btn btn-outline-success btn-block">Create</button> <br>
     
      
    </div>
   
  </form>
</div><br>
{% endblock body %}

templates/appointment/appointment_details.html
{% extends 'base/base.html' %}
{% load crispy_forms_tags %}


{% block head %}
    
{% endblock head %}
    

{% block body %}

<div class="container">
    <div class="card m-2">
        <div class="m-2">
            <h6>Name: {{data.name}}</h6>
            <h6>Email: {{data.email}}</h6>
            <h6>Phone: {{data.phone}}</h6>
            <h6>Department: {{data.department}}</h6>
            <h6>Doctor: {{data.doctor}}</h6>

            {% if data.report %}
            <h6>Report:</h6>
                <p><a href="{{data.report.url}}">{{data.report}}</a>.</p>
            {% endif %}
            
            <h6>Description:</h6>
            <p>{{data.describe_your_problems}}</p>
        </div>
    </div>


    {% if request.user.is_doctor %}
        <div class="card">
            <div class="m-2">
                <form method="post">
                {%csrf_token %}
                <h2>Answer Here</h2>
                {{form | crispy}}
                <input type="submit" class="btn btn-success" value="Answer" />
                </form>
            </div>
        </div>
    {% endif %}

    <hr>

 <!-- prescription  -->

    <!-- prescription start  -->
    
    <div class="card">
        <div class="m-2">
            
            <div class="prescription-header">
                <h1 style="text-align: center; color:rgb(7, 77, 30)">Needs Health Care</h1>
                <hr style="border-top: 2px dashed #8c8b8b;">
                <div class="prescription-body">
                    {%for answer in record %}
                    <div class="card">
                        <div class="m-2">
                        <strong> Medicine one: <small> {{answer.medicine_one}}</small></strong> <br><br>
                        <strong> Medicine two: <small> {{answer.medicine_two}}</small></strong> <br><br>
                        <strong> Medicine three: <small> {{answer.medicine_three}}</small></strong> <br><br>
                        <strong> Medicine others: <small> {{answer.medicine_others}}</small></strong> <br><br>
                        <strong> Medication rules: <small> {{answer.medicine_eating_time}}</small></strong> <br><br>
                        <hr>
                        <strong> Advice: <small> {{answer.advice}}</small></strong> <br><br>

                        <a target="_blank" href="{% url 'prescription_pdf' _id=answer.id %}">Generate & Download PDF</a> 
                        
                    </div>
                </div>  <br>
    
                    {%endfor %} 
    
                </div>
            </div>
        </div>
        
    </div>
    
    <!-- end prescription   -->

</div>

{% endblock body %}

templates/appointment/appointment_list.html
{% extends 'base/base.html' %}
{% load crispy_forms_tags %}


{% block head %}
<style>
    .card:hover{
    background-color:rgba(244, 244, 244, 0.8);
    transition: color .3s ease-in-out, box-shadow .5s ease-in-out;
    box-shadow: inset 140ch 0 0 0 rgba(255, 228, 242, 0.8);
    transform: scale(1.1);
    transition: transform .5s;
    
}
</style>
    
{% endblock head %}
    

{% block body %}
<div class="container">
  <div class="mt-5">
    {% if total_appointment %}
      <h5 style="color:rgb(150, 185, 93);" class="text">You have total {{ total_appointment }} appointments.</h5>
  {% else %}
    <h5 class="text-center" style="color:red;">You don't have any appointment yet.</h5>
  {% endif %}
    <div class="row">
      
        {% for data in total %}
        <div class="col-lg-4">
    
            <div class="card" style="width: 18rem;">
            <h5 class="card-header">{{data.name}}</h5>
            <h5 class="card-header">{{data.email}}</h5>
            <h5 class="card-header">{{data.phone}}</h5>
            <small class="card-header">{{data.department}}</small>
            <small class="card-header">{{data.doctor}}</small>
            <div class="card-body sm">
                <a href="{% url 'user_appointments' _id=data.id %}" class="btn btn-primary">Read More</a>
            </div>
      </div>
      <br>
        </div>
      {% endfor %}
    </div>
  </div>

  

</div>



{% endblock body %}

templates/appointment/doctor_dropdown_list_options.html
<option value="">---------</option>
{% for doctor in doctors %}
<option value="{{ doctor.pk }}">{{ doctor.name }}</option>
{% endfor %}

templates/appointment/home.html
{% extends 'base/base.html' %}
{% load crispy_forms_tags %}

{% block body %}
<div class="container">
  <div class="row">
    <div class="col-md-8">
      <div class="m-2">
        <form method="post" id="PatientForm" data-doctors-url="{% url 'ajax_load_doctors' %}" class="form-horizontal" role="form" enctype="multipart/form-data">
          {% csrf_token %}
          {{ form | crispy }}
          <input type="submit" value="Create" class="btn btn-info">
          </form>
        </div>
    </div>

    <div style="text-align:right;" class="col-md-4">
      <div class="m-2">
        <h5>Short Links </h5>
        
        {% if user.is_authenticated %}
          <a href="{% url 'my_appointments' %}">My appointments</a> &nbsp;
        {% endif %}
        <br>
        
        {% if user.is_doctor or user.is_superuser %}
          <a href="{% url 'total_appointments' %}">All appointments</a> &nbsp;
        {% endif %}
        
      </div>
    </div>
  </div>
</div>

{% endblock body %}



{% block script %}
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

<script>
  $('#id_department').change(function () {
    const url = $("#PatientForm").attr("data-doctors-url");  
    const departmentId = $(this).val(); 

    $.ajax({                      
      url: url, 
      data: {
          'department_id': departmentId 
      },
      success: function (data) {   
          $("#id_doctor").html(data);
      }
    });
  });
</script>
  
{% endblock script %}
    

    

templates/appointment/prescription_pdf.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Needs Health Care </title>

    <style>
        table {
          font-family: arial, sans-serif;
          border-collapse: collapse;
          width: 100%;
        }
        
        td, th {
          border: 1px solid #dddddd;
          text-align: left;
          padding: 8px;
        }
        
        tr:nth-child(even) {
          background-color: #dddddd;
        }
        .right {
            text-align: right;
            }
        </style>
</head>
<body>
    <h1 style="text-align: center; color:rgb(7, 77, 30); font-size: 40px;">Needs Health care</h1><br>

    <!-- patient info  -->
    <table>
        <tr>
          <th>Patient Info</th>
          <th class="right">Doctor Info</th>  
        </tr>

        <tr>
          <td><p>Patient name: {{record.patient.user.username}}</p></td>
          <td class="right"> <strong> Doctor name:</strong>  Helen Bennett</td>
        </tr>
        
        <tr>
          <td>Age: {{record.patient.age}}</td>
          <td class="right"> <strong> Department:</strong>  {{record.patient.doctor.department.name}}</td>
        </tr>

        <tr>
          <td>Sex: {{record.patient.sex}}</td>
          <td class="right"> <strong> Date:</strong>  {{record.date}}</td>
        </tr>

      </table> 
<hr>

    <table>
        <tr>
          <th>Medicine Info</th>
          <th class="right">Medication rules</th>  
        </tr>

        <tr>
          <td><p style="font-size: 15px;"><strong>Medicine 1: </strong> {{ record.medicine_one }}</p></td>
          <td class="right"> <strong> Medication:</strong>  {{record.medicine_eating_time}}</td>
        </tr>
        
        <tr>
            <td><p style="font-size: 15px;"><strong>Medicine 2: </strong> {{ record.medicine_two }}</p></td>
        </tr>

        <tr>
            <td><p style="font-size: 15px;"><strong>Medicine 3: </strong> {{ record.medicine_three }}</p></td>
        </tr>
        <tr>
            <td><p style="font-size: 15px;"><strong>Medicine others: </strong> {{ record.medicine_others }}</p></td>
        </tr>
        

      </table>
      <div class="card">
        <p style="font-size: 15px;">Medication rules</p>
        {{ record.medicine_eating_time }}
      </div>
    <hr>

    <div class="card">
        <div class="m-2">
            <h1 style="font-size: 20px;">Medicale Test</h1>
            {{ record.test }}
            <hr>
        </div>
    </div>

    <div class="card">
        <div class="m-2">
            <h1 style="font-size: 20px;">Advice</h1>
            {{ record.advice }}
            
        </div>
    </div>


    
</body>
</html>